  version: "3"
  services:
    db:
          image: postgres
          container_name: db
          environment:
              - POSTGRES_USER=admin
              - POSTGRES_PASSWORD=admin123
              - POSTGRES_DB=testdb
              - PGDATA=/var/lib/postgresql/data/pgdata
          ports:
              - 5000:5432
          volumes:
              - pgdata:/var/lib/postgresql/data
          restart: always
    springapp:
      build: .
      container_name: getirbackendapp
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: admin123
      ports:
        - 8080:8080
      restart: always
      depends_on:
        - db
  networks:
      getirnetwork:
          driver: bridge

  volumes:
      pgdata:
